openapi: 3.0.0
info:
  version: 1.0.0
  title: 行政オープンデータを収集して取得できるAPI一覧
servers:
  - url: https://takukobayashi.github.io/GovernmentOpenDataWebAPI/api/v1
    description: APIの既定となるURL
paths:
  category/{category}/list.json:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties: {}
      parameters:
        - in: path
          name: category
          required: true
          schema:
            type: string
            enum:
              - toilet
              - park
              - wireless
          description: categoryデータの一覧
  "{province}/{city}/{category}.json":
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties: {}
      parameters:
        - in: path
          name: province
          required: true
          schema:
            type: string
          description: 都道府県
        - in: path
          name: city
          required: true
          schema:
            type: string
          description: 市区町村
        - in: path
          name: category
          required: true
          schema:
            type: string
            enum:
              - toilet
              - park
              - wireless
          description: categoryデータの一覧
  keyword/{keyword}/list.json:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties: {}
      parameters:
        - in: path
          name: keyword
          required: true
          schema:
            type: string
            enum:
              - 包括
              - 避難
              - 広域
              - 救護
              - 遊び場
              - あんしん
              - 区立
              - スポーツ
              - 館
              - 幼稚園
              - 病
              - キッズ
              - 拠点
              - 回収
              - 自転車
              - 集会
              - 無線
              - 文京
              - 箇所
              - 園
              - 荒川
              - 青梅
              - 病院
              - 文化
              - 準拠
              - 標準
              - 診療
              - 事
              - 個所
              - ポイント
              - 保育
              - 公共
              - 緑地
              - 子育て
              - 投票
              - 駐輪場
              - 公園
              - 応急
              - 機関
              - 観光
              - 運動
              - クラブ
              - 震災
              - 産
              - 自立
              - 放課後
              - 訪問
              - 支援
              - 製作
              - 盲導犬
              - 点字
              - 聴覚
              - 盲人
              - 宿
              - 授産
              - 宿泊
              - 北
              - 休養
              - 協議
              - 相談
              - 家庭
              - センター
              - 心身
              - 会館
              - ハウス
              - 人材
              - 発達
              - 区
              - 保健
              - 市町村
              - 更生
              - 政令
              - 喫煙
              - 授乳
              - 杉並
              - 掌
              - 番号
              - 八重洲
              - 板橋
              - 椅子
              - 公
              - 食堂
              - 葬儀
              - 情報
              - 福祉
              - 敬老
              - 作業
              - その他
              - コート
              - プール
              - 形式
              - サテライト
              - 低額
              - 給水
              - 認可
              - 乳児
              - 母子
              - 児童
              - 援助
              - 出版
              - ホーム
              - グループ
              - 保護
              - 中核
              - 指定
              - みどころ
              - プラザ
              - おむつ
              - 連絡
              - バリア
              - 脳
              - 停留所
              - 東西
              - ダウンロード
              - 時点
              - 名
              - 受取
              - 日常
              - 犬
              - たま
              - 保管
              - 記念
              - スポット
              - 庁舎
              - 香
              - 谷原
              - 広場
              - 時給
              - 石神井
              - ひろば
              - サポート
              - 時
              - 風水害
              - 団体
              - 音響
              - 優待
              - 範囲
              - 選定
              - 地区
              - 生涯
              - 公会堂
              - 学校
              - 電気
              - 史跡
              - 清掃
              - 産業
              - 駐車
              - 置場
              - 備蓄
              - 火葬
              - 調達
              - 浄水
              - 管
              - 器材
              - 別表
              - 総務
              - 位置
              - 体育
              - 向山
              - 出張
              - 中高
              - 共同
              - 青少年
              - 分室
              - 交流
              - 区民
              - 美術
              - 分館
              - 学習
              - リサイクル
              - 循環
              - 中村
              - 練馬
              - 土木
              - 帰宅
              - レクリエーション
              - 青年
              - からだ
              - 子供
              - 市営
              - 荏原
              - 大井
              - エネルギー
              - 利用
              - 認証
              - 学童
              - 設置
              - 緑
              - 密着
              - 土のう
              - 家電
              - 掲載
              - 特設
              - 休けい
              - 郊外
              - 振興
              - 勤労
              - だ
              - 高齢
              - 羽村
              - 稲城
              - 公民
              - 野市
              - 小平
              - 小金井
              - 推進
              - 類似
              - 博物
              - 武蔵野
              - 昭島
              - 調布
              - 町田
              - 日野
              - 東村山
              - 立川
              - 八王子
              - 西
              - 福生
              - 国立
              - 東久留米
              - 清瀬
              - 多摩
              - 東大和
              - 狛江
              - 再生
              - 焼却
              - 国分寺
              - 三鷹
              - 小笠原
              - 青ヶ島
              - 八丈
              - 御蔵島
              - 三宅
              - 神津島
              - 新島
              - 利島
              - 大島
              - 奥多摩
              - 檜原
              - 日の出
              - 瑞穂
              - 選管
              - 旅客
              - 行
              - トンネル
              - 非行
              - 評価
              - 行政
              - フォーラム
              - 名勝
              - 発
              - 堺
              - 集合
              - 飲食
              - シェルター
              - 一覧
              - 公私
              - マップ
              - 初動
              - 基地
              - 水上
              - 滞在
              - 役所
              - 私立
              - 中学校
              - ショップ
              - 消費
              - 保養
              - 浴場
              - データ
              - 本部
              - 路
              - 救出
              - 電信
              - ライン
              - 陸上
              - 海上
              - 貯水槽
              - 固定
              - 財団
              - 室
              - 機能
              - 活動
              - 倉庫
              - 灰
              - 子ども
              - 参画
              - 便所
              - 斎場
              - 置き場
              - 橋梁
              - 伝統
              - ハイツ
              - 複合
              - 港
              - 大使
              - ルート
              - 店舗
              - 薬局
              - 施術
              - 開設
              - 変更
              - 不在
              - リング
              - パス
              - 声
          description: keywordデータの一覧
  "{province}/{city}/{keyword}.json":
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties: {}
      parameters:
        - in: path
          name: province
          required: true
          schema:
            type: string
          description: 都道府県
        - in: path
          name: city
          required: true
          schema:
            type: string
          description: 市区町村
        - in: path
          name: keyword
          required: true
          schema:
            type: string
            enum:
              - 包括
              - 避難
              - 広域
              - 救護
              - 遊び場
              - あんしん
              - 区立
              - スポーツ
              - 館
              - 幼稚園
              - 病
              - キッズ
              - 拠点
              - 回収
              - 自転車
              - 集会
              - 無線
              - 文京
              - 箇所
              - 園
              - 荒川
              - 青梅
              - 病院
              - 文化
              - 準拠
              - 標準
              - 診療
              - 事
              - 個所
              - ポイント
              - 保育
              - 公共
              - 緑地
              - 子育て
              - 投票
              - 駐輪場
              - 公園
              - 応急
              - 機関
              - 観光
              - 運動
              - クラブ
              - 震災
              - 産
              - 自立
              - 放課後
              - 訪問
              - 支援
              - 製作
              - 盲導犬
              - 点字
              - 聴覚
              - 盲人
              - 宿
              - 授産
              - 宿泊
              - 北
              - 休養
              - 協議
              - 相談
              - 家庭
              - センター
              - 心身
              - 会館
              - ハウス
              - 人材
              - 発達
              - 区
              - 保健
              - 市町村
              - 更生
              - 政令
              - 喫煙
              - 授乳
              - 杉並
              - 掌
              - 番号
              - 八重洲
              - 板橋
              - 椅子
              - 公
              - 食堂
              - 葬儀
              - 情報
              - 福祉
              - 敬老
              - 作業
              - その他
              - コート
              - プール
              - 形式
              - サテライト
              - 低額
              - 給水
              - 認可
              - 乳児
              - 母子
              - 児童
              - 援助
              - 出版
              - ホーム
              - グループ
              - 保護
              - 中核
              - 指定
              - みどころ
              - プラザ
              - おむつ
              - 連絡
              - バリア
              - 脳
              - 停留所
              - 東西
              - ダウンロード
              - 時点
              - 名
              - 受取
              - 日常
              - 犬
              - たま
              - 保管
              - 記念
              - スポット
              - 庁舎
              - 香
              - 谷原
              - 広場
              - 時給
              - 石神井
              - ひろば
              - サポート
              - 時
              - 風水害
              - 団体
              - 音響
              - 優待
              - 範囲
              - 選定
              - 地区
              - 生涯
              - 公会堂
              - 学校
              - 電気
              - 史跡
              - 清掃
              - 産業
              - 駐車
              - 置場
              - 備蓄
              - 火葬
              - 調達
              - 浄水
              - 管
              - 器材
              - 別表
              - 総務
              - 位置
              - 体育
              - 向山
              - 出張
              - 中高
              - 共同
              - 青少年
              - 分室
              - 交流
              - 区民
              - 美術
              - 分館
              - 学習
              - リサイクル
              - 循環
              - 中村
              - 練馬
              - 土木
              - 帰宅
              - レクリエーション
              - 青年
              - からだ
              - 子供
              - 市営
              - 荏原
              - 大井
              - エネルギー
              - 利用
              - 認証
              - 学童
              - 設置
              - 緑
              - 密着
              - 土のう
              - 家電
              - 掲載
              - 特設
              - 休けい
              - 郊外
              - 振興
              - 勤労
              - だ
              - 高齢
              - 羽村
              - 稲城
              - 公民
              - 野市
              - 小平
              - 小金井
              - 推進
              - 類似
              - 博物
              - 武蔵野
              - 昭島
              - 調布
              - 町田
              - 日野
              - 東村山
              - 立川
              - 八王子
              - 西
              - 福生
              - 国立
              - 東久留米
              - 清瀬
              - 多摩
              - 東大和
              - 狛江
              - 再生
              - 焼却
              - 国分寺
              - 三鷹
              - 小笠原
              - 青ヶ島
              - 八丈
              - 御蔵島
              - 三宅
              - 神津島
              - 新島
              - 利島
              - 大島
              - 奥多摩
              - 檜原
              - 日の出
              - 瑞穂
              - 選管
              - 旅客
              - 行
              - トンネル
              - 非行
              - 評価
              - 行政
              - フォーラム
              - 名勝
              - 発
              - 堺
              - 集合
              - 飲食
              - シェルター
              - 一覧
              - 公私
              - マップ
              - 初動
              - 基地
              - 水上
              - 滞在
              - 役所
              - 私立
              - 中学校
              - ショップ
              - 消費
              - 保養
              - 浴場
              - データ
              - 本部
              - 路
              - 救出
              - 電信
              - ライン
              - 陸上
              - 海上
              - 貯水槽
              - 固定
              - 財団
              - 室
              - 機能
              - 活動
              - 倉庫
              - 灰
              - 子ども
              - 参画
              - 便所
              - 斎場
              - 置き場
              - 橋梁
              - 伝統
              - ハイツ
              - 複合
              - 港
              - 大使
              - ルート
              - 店舗
              - 薬局
              - 施術
              - 開設
              - 変更
              - 不在
              - リング
              - パス
              - 声
          description: keywordデータの一覧
