on:
  push:
    branches:
    - master

name: Data Import and Export
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          TZ: ${{ secrets.TZ }}
        options: >-
          --health-cmd "mysqladmin ping -h 127.0.0.1"
          --health-interval 20s
          --health-timeout 10s
          --health-retries 10
    steps:
    - uses: actions/checkout@v4
    - name: setup ubuntu
      run: |
        sudo apt-get --quiet update --yes
        sudo apt-get --quiet install --yes default-mysql-client git
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install
      run: yarn install
    - name: Register .env
      working-directory: ./
      env:
        MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
        MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
        MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        echo "MYSQL_USERNAME=${MYSQL_USERNAME}" >> ./.env
        echo "MYSQL_HOST=${MYSQL_HOST}" >> ./.env
        echo "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}" >> ./.env
        echo "MYSQL_DATABASE=${MYSQL_DATABASE}" >> ./.env
        echo "MYSQL_PORT=${MYSQL_PORT}" >> ./.env
        echo "DATABASE_URL=${DATABASE_URL}" >> ./.env
    - name: prisma setup
      run: yarn run prisma generate
    - name: prisma migrate
      run: yarn run prisma migrate reset --force
    - name: data setup
      run: yarn run commander seeder
    - name: data import
      run: yarn run commander data import
    - name: export sql
      run: yarn run commander data export
    - name: upload sql
      run: |
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git add resources/sqls/
        git commit --allow-empty -m "add `date +%Y-%m-%d-%H:%M:%S` sqls"
        git checkout .
        git pull --rebase origin export-sql
        git push origin export-sql
    - uses: actions/upload-artifact@v4
      with:
        name: sqls
        path: resources/sqls