on:
  push:
    branches:
    - master

name: Data Import and Export
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: hoge
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          TZ: ${{ secrets.TZ }}
        options: >-
          --health-cmd "mysqladmin ping -h 127.0.0.1"
          --health-interval 20s
          --health-timeout 10s
          --health-retries 10
    steps:
    - uses: actions/checkout@v4
    - name: setup ubuntu
      run: |
        sudo apt-get --quiet update --yes
        sudo apt-get --quiet install --yes default-mysql-client
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install
      run: yarn install
    - name: prisma setup
      run: yar run prisma generate
    - name: prisma migrate
      run: yarn run prisma migrate reset --force
    - name: data setup
      run: yarn run commander seeder
    - name: data import
      run: yarn run commander data import
    - name: data import
      run: yarn run commander data export
    - uses: actions/upload-artifact@v4
      with:
        name: sqls
        path: resources/sqls